---
- name: ensure screenshot directory exists
  ansible.builtin.file:
    path: "{{ screenshotDir }}"
    state: directory

- name: set hostname
  ansible.builtin.command: "{{ item }}"
  loop:
    - 'sudo scutil --set ComputerName {{ hostname }}'
    - 'sudo scutil --set LocalHostName {{ hostname }}'
    - 'sudo scutil --set HostName {{ hostname | lower }}'
  become: true

- name: install casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop:
    - 'google-chrome'
    - 'steam'

- name: set macos settings
  ansible.builtin.command: "{{ item }}"
  loop:
    - 'defaults write com.apple.dock persistent-others -array'
    - 'defaults write com.apple.dock persistent-apps -array'
    - 'defaults write com.apple.dock show-recents -bool false'
    - 'defaults write com.apple.dock "tilesize" -int "48"'
    - 'defaults write com.apple.dock "autohide" -bool "false"'
    - 'defaults write com.apple.dock "mru-spaces" -bool "false"'
    - 'defaults write com.apple.screencapture location {{ screenshotDir }}'
    - 'defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false'
