" Stop VI compatibility
set nocompatible

if filereadable(expand("~/.vimrc_background"))
        let base16colorspace=256
        source ~/.vimrc_background
endif
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Show ruler
set ruler

" Show line numbers over there <-
set relativenumber
set number

" Show mode
set showmode

" Expand tabs to spaces
set expandtab

" Autoindent copies the previously line's indentation
set autoindent

" Smartindent automatically adds more indents in C-like files
set smartindent

" Tabs have this many spaces when editing
set softtabstop=4

" Tabs have this many spaces
set tabstop=4

" Highlight current line
set cursorline

" Set colored column
set colorcolumn=80

" Allow proper backspacing
set backspace=2

" \W will remove all trailing whitespace
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>

" Enable syntax highlighting
syntax on

"Enable file-specific indentation
filetype plugin indent on

" Remape ESC to jk
imap jk <Esc>

" Turn off the arrow keys because LEARNING
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

" Move up and down by buffer line, not actual line
nnoremap j gj
nnoremap k gk

