---
- name: set aliases
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "~/.zshrc"
    line: "{{ item }}"
  loop:
    - 'alias gs="git status"'
    - 'alias gl="git branch --list"'
    - 'alias la="ls -lah"'
    - 'alias clera="clear"'

- name: start ssh agent
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "~/.zshrc"
    line: "{{ item }}"
  loop:
    - 'eval "$(ssh-agent -s)" &>/dev/null'
    - 'ssh-add --apple-use-keychain ~/.ssh/id_ed25519 &>/dev/null'

- name: set terminal prompt
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "~/.zshrc"
    line: "{{ item }}"
  loop:
    - 'PROMPT_EOL_MARK=""'
    - 'PROMPT="%F{green}%n%f@%F{blue}%m:%~%f$ "'
    - 'export CLICOLOR=1'

- name: add ansible to path
  ansible.builtin.lineinfile:
    state: present
    create: true
    path: "~/.zshrc"
    line: "PATH=$PATH:/Users/mario/Library/Python/3.9/bin/"

- name: copy vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: copy colima config
  ansible.builtin.copy:
    src: colima.yaml
    dest: "{{ ansible_env.HOME }}/.colima/default/colima.yaml"

- name: install homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - colima
    - docker
    - golang
    - awscli

- name: start homebrew services
  ansible.builtin.command: "brew services restart {{ item }}"
  loop:
    - colima

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop:
    - visual-studio-code
    - iterm2

- name: set up git
  ansible.builtin.import_tasks: git.yml
